GET http://localhost:8085/spring-hibernate/api/v1/product/all

###

GET http://localhost:8085/spring-hibernate/api/v1/product/1

###

DELETE http://localhost:8085/spring-hibernate/api/v1/product/delete/9

###

POST http://localhost:8095/spring-hibernate/api/v1/product
Content-Type: application/json

{
  "category": "paints",
  "title": "green",
  "price": 19
}

###

PUT http://localhost:8095/spring-hibernate/api/v1/product
Content-Type: application/json

{
  "id": 1,
  "category": "paints",
  "title": "Brass scorpio",
  "price": 30
}

###

GET http://localhost:8095/spring-hibernate/api/v1/product/basket/all

###

DELETE http://localhost:8095/spring-hibernate/api/v1/product/basket/remove/10

###

POST http://localhost:8095/spring-hibernate/api/v1/product/basket/add/2

###

GET http://localhost:8095/spring-hibernate/api/v1/product/filter

###

GET http://localhost:8095/spring-spring-app/api/v1/user/1

###

GET http://localhost:8095/spring-spring-app/api/v1/user/all
